### ISSUE TITLE
Not able to build nightly

### ISSUE THREAD

**Issue by reggaemuffin** [emk/heroku-buildpack-rust#36] opened 2018-10-30 10:19 UTC
When I specify the buildpack to use nightly, I get this on heroku:

```
-----> Rust app detected
-----> Downloading rustup
-----> Using rustup to install Rust channel nightly
info: downloading installer
error: invalid toolchain name: 'nightly
 !     Push rejected, failed to compile Rust app.
 !     Push failed
```

**Comment by emk** [comment] 2018-10-30 15:25
Good question.

Did you set it to use `nightly`, or `'nightly` (with an extra leading quote)? That part of the error looks suspicious.

**Comment by reggaemuffin** [comment] 2018-10-30 15:48
I tried it as Rustconfig version variable, as this other file that just contains it, both with nightly or 1.30.0-nightly and other combinations. So far none of them worked.

**Comment by emk** [comment] 2018-10-31 11:49
You _may_ have a syntax error somewhere in your `RustConfig` file that's passing in an extra `'` character. Can you please post your `RustConfig` file?

**Comment by reggaemuffin** [comment] 2018-10-31 13:50
@emk 

`RustConfig`: `VERSION=nightly`

![image](https://user-images.githubusercontent.com/644950/47792429-4dddbb80-dd1c-11e8-9a73-d873ba9af380.png)


also tried

`rust-toolchain`: `1.31.0-nightly`
`rust-toolchain`: `1.30.0-nightly`
`rust-toolchain`: `1.29.0-nightly`
`rust-toolchain`: `nightly`

And a few other permutations of these. If you want I can produce the other errors. The current one is with above mentioned RustConfig

**Comment by emk** [comment] 2018-11-01 15:13
OK, so the code which is failing is here:

```sh
    curl https://sh.rustup.rs -sSf > rustup.sh
    chmod u+x rustup.sh
    echo "-----> Using rustup to install Rust channel $VERSION"
    ./rustup.sh -y --default-toolchain "$VERSION"
```

This looks like a potential problem with `rustup.rs` and the `--default-toolchain` argument? To diagnose this, you could try running the following inside a container:

```sh
# Start a container using a Heroku-like image.
docker run --rm -it heroku/heroku:18 bash

# Install Rust nightly.
curl https://sh.rustup.rs -sSf > rustup.sh
chmod u+x rustup.sh
./rustup.sh -y --default-toolchain nightly
```

This seems to work correctly for me. So either the problem was an intermittent issue with rustup.rs, or it only occurs when actually running on Heroku.

If you are still seeing this problem today, I can try setting up a test project for `nightly` and see what happens.

**Comment by reggaemuffin** [comment] 2018-11-01 15:42
Tried it and same error as mentioned above.

**Comment by emk** [comment] 2018-11-02 14:10
Hmm, this is seriously weird, and it sounds like a `rustup` or `heroku/heroku:18` issue of some kind.

Everything in my last comment worked for me yesterday, and if I'm reading your comment correctly, basic rustup operations fail for you (but not for me) with none of my buildpack code involved.

I can't think of anything that would cause this. I'll keep thinking about it and see if anything comes to mind. :-( Let me know if you think of something.

**Comment by emk** [comment] 2018-12-09 00:16
Hello again. Have you found a solution for this problem yet? Has it gone away on its own?

If the problem still exists, could you point me at a small GitHub repo which fails?

Thank you for any further information you can provide!

**Comment by reggaemuffin** [comment] 2018-12-09 09:38
I was trying to deploy https://github.com/valeriansaliou/vigil which requires nightly and was not able to get it to work in any of the ways specified, not with a rust toolchain file and not with rustconfig.

So far I have shelved that endeavor but would love to try again! No solution found sadly

**Comment by emk** [comment] 2018-12-09 16:04
I've made some progress with this!

If you have an existing project, you may need to [clear your Heroku build cache](https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache). This _shouldn't_ be an issue, because we attempt to auto-update `rustup` and the compiler toolchain, but it's worth a shot.

Or you may be able to clone `vigil` a new copy of `vigil` and deploy it like this:

```sh
git clone https://github.com/valeriansaliou/vigil.git
cd vigil
heroku create --buildpack emk/rust
echo "nightly-2018-08-24" > rust-toolchain
git add rust-toolchain
git commit -m "Specify Rust version"
git push heroku master
```

I'm running the later commands as we speak, and it has already made it well past the point that it broke for you.

**Comment by emk** [comment] 2018-12-09 16:10
I have confirmed that I was able to deploy `vigil` using the instructions above! I'm going to close this issue, but feel free to reopen it if you've cleared your build cache, added a `rust-toolchain` file, and still can't get things to work. Thank you for reporting this!

**Closed by emk** 2018-12-09 16:10 UTC

**Comment by reggaemuffin** [comment] 2018-12-09 18:15
Thank you for the quick fix, I will try it out right now and report back!
